//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sanzo.CheckBill {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CheckBill.WsTrackAndTraceSoap")]
    public interface WsTrackAndTraceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadTrackAndTrace", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable LoadTrackAndTrace(string companyid, string user, string pass, string mabpbk, string mabangke);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsTrackAndTraceSoapChannel : sanzo.CheckBill.WsTrackAndTraceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsTrackAndTraceSoapClient : System.ServiceModel.ClientBase<sanzo.CheckBill.WsTrackAndTraceSoap>, sanzo.CheckBill.WsTrackAndTraceSoap {
        
        public WsTrackAndTraceSoapClient() {
        }
        
        public WsTrackAndTraceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsTrackAndTraceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsTrackAndTraceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsTrackAndTraceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable LoadTrackAndTrace(string companyid, string user, string pass, string mabpbk, string mabangke) {
            return base.Channel.LoadTrackAndTrace(companyid, user, pass, mabpbk, mabangke);
        }
    }
}
