//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.28.248.1;Initial Catalog=ipinternational_com_vn;Persist Security " +
            "Info=True;User ID=ipinternational;Password=cG8ckhD79y")]
        public string ipinternational_com_vnConnectionString {
            get {
                return ((string)(this["ipinternational_com_vnConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=dichvuchothue_com_vn;Persist Security Info=Tr" +
            "ue;User ID=dichvuchothue;Password=v2qHkgP2EA")]
        public string chuyenchothue_comConnectionString {
            get {
                return ((string)(this["chuyenchothue_comConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=vanmatbich_com;Persist Security Info=True;Use" +
            "r ID=congnghiep;Password=UG8P7hz3yk")]
        public string tuvannetviet_comConnectionString {
            get {
                return ((string)(this["tuvannetviet_comConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=maynganhcongnghiep_com;Persist Security Info=" +
            "True;User ID=maynganhcongnghiep;Password=AtQuwp2DXY")]
        public string chuyenchothue_comConnectionString1 {
            get {
                return ((string)(this["chuyenchothue_comConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=dolotgiasi_vn;Persist Security Info=True;User" +
            " ID=dolotgiasi;Password=CCA66Xx26tbCwPc")]
        public string chuyenchothue_comConnectionString2 {
            get {
                return ((string)(this["chuyenchothue_comConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=linhkiendocmientrung_com_vn;Persist Security " +
            "Info=True;User ID=namtam;Password=9HvZX2d89Q")]
        public string vanmatbich_comConnectionString {
            get {
                return ((string)(this["vanmatbich_comConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=shopbacsi_com;Persist Security Info=True;User" +
            " ID=shopbacsi;Password=wrB2Q2f83y")]
        public string vanmatbich_comConnectionString1 {
            get {
                return ((string)(this["vanmatbich_comConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=happybuy_com_vn;Persist Security Info=True;Us" +
            "er ID=happybuy;Password=p6Kg2bQdr2")]
        public string vanmatbich_comConnectionString2 {
            get {
                return ((string)(this["vanmatbich_comConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=beta.happybuy.com.vn;Initial Catalog=happybuy_com_vn;Persist Security" +
            " Info=True;User ID=happybuy;Password=p6Kg2bQdr2")]
        public string happybuy_com_vnConnectionString {
            get {
                return ((string)(this["happybuy_com_vnConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.28.248.1;Initial Catalog=happybuy_com_vn;Persist Security Info=Tr" +
            "ue;User ID=truongnt;Password=GFHkpgp73P")]
        public string vanmatbich_comConnectionString3 {
            get {
                return ((string)(this["vanmatbich_comConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=USER002-PC;Initial Catalog=KLN;Integrated Security=True")]
        public string happybuy2_com_vnConnectionString {
            get {
                return ((string)(this["happybuy2_com_vnConnectionString"]));
            }
        }
    }
}
